"""GENERATED by tools/extract_reference.py from
Z:/Joseph/250514_B2_000/ROI_analysis.ipynb
Do not edit; re-run the extractor instead."""
import numpy as np
from scipy import stats
from scipy.linalg import eig

def aaft_surrogate(data):
    """
    Amplitude Adjusted Fourier Transform (AAFT) surrogate generation.
    """
    sorted_original = np.sort(data)
    ranks = stats.rankdata(data, method='ordinal') - 1
    gaussian = np.random.randn(len(data))
    fft_gaussian = np.fft.fft(gaussian)
    phases_gaussian = np.angle(fft_gaussian)
    fft_original = np.fft.fft(data)
    amplitudes = np.abs(fft_original)
    fft_surrogate = amplitudes * np.exp(1j * phases_gaussian)
    surrogate = np.real(np.fft.ifft(fft_surrogate))
    surrogate_ranks = stats.rankdata(surrogate, method='ordinal') - 1
    final_surrogate = sorted_original[surrogate_ranks]
    return final_surrogate

def calculate_synchronicity_index(corr_matrix, fluorescence_data=None, n_surrogates=20, min_cluster_size=3, significance_threshold=2.0, verbose=True):
    """
    Calculate synchronicity index based on FluoroSNNAP's SCA method.
    
    Parameters:
    -----------
    corr_matrix : ndarray, shape (M, M)
        Correlation matrix of M ROIs/neurons
    fluorescence_data : ndarray, shape (M, T), optional
        Original fluorescence traces (M neurons × T timepoints)
        Use your dFz[order_full] or dFz data
    n_surrogates : int, default=20
        Number of surrogate datasets to generate
    min_cluster_size : int, default=3
        Minimum number of neurons required for a synchronization cluster
    significance_threshold : float, default=2.0
        Number of standard deviations above surrogate mean for significance
    verbose : bool, default=True
        Print progress information
        
    Returns:
    --------
    results : dict
        Dictionary containing all SCA results
    """
    M = corr_matrix.shape[0]
    if verbose:
        print(f'Performing Synchronization Cluster Analysis on {M} ROIs...')
    eigenvalues, eigenvectors = eig(corr_matrix)
    eigenvalues = np.real(eigenvalues)
    eigenvectors = np.real(eigenvectors)
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]
    if verbose:
        print(f'Largest eigenvalue: {eigenvalues[0]:.4f}')
    if fluorescence_data is not None:
        T = fluorescence_data.shape[1]
        surrogate_eigenvalues = np.zeros((M, n_surrogates))
        if verbose:
            print(f'Generating {n_surrogates} surrogates for significance testing...')
        for n in range(n_surrogates):
            if verbose and (n + 1) % 5 == 0:
                print(f'  Surrogate {n + 1}/{n_surrogates}')
            F_surrogate = np.zeros_like(fluorescence_data)
            for i in range(M):
                F_surrogate[i, :] = aaft_surrogate(fluorescence_data[i, :])
            R = np.corrcoef(F_surrogate)
            eig_sur, _ = eig(R)
            eig_sur = np.real(eig_sur)
            eig_sur = np.sort(eig_sur)[::-1]
            surrogate_eigenvalues[:, n] = eig_sur
        lambda_sur = np.mean(surrogate_eigenvalues, axis=1)
        SD_sur = np.std(surrogate_eigenvalues, axis=1, ddof=1)
        if verbose:
            print(f'Surrogate mean (largest eigenvalue): {lambda_sur[0]:.4f} ± {SD_sur[0]:.4f}')
    else:
        if verbose:
            print('Warning: No fluorescence data provided. Using simplified calculation.')
        lambda_sur = np.ones(M)
        SD_sur = np.zeros(M)
    SI = np.zeros(M)
    for i in range(M):
        if eigenvalues[i] > lambda_sur[i] + significance_threshold * SD_sur[i]:
            SI[i] = (eigenvalues[i] - lambda_sur[i]) / (M - lambda_sur[i])
        else:
            SI[i] = 0.0
    n_clusters = np.sum(SI >= 0.01)
    cluster_indices = np.where(SI >= 0.01)[0]
    if verbose:
        print(f'Number of significant clusters (SI >= 0.01): {n_clusters}')
    PI = np.zeros((M, max(n_clusters, 1)))
    for k, cluster_idx in enumerate(cluster_indices):
        lambda_k = eigenvalues[cluster_idx]
        v_k = eigenvectors[:, cluster_idx]
        PI[:, k] = lambda_k * v_k ** 2
    if n_clusters > 0:
        cluster_assignment = np.argmax(PI, axis=1)
        cluster_sizes = np.array([np.sum(cluster_assignment == k) for k in range(n_clusters)])
        valid_clusters = cluster_sizes >= min_cluster_size
        n_valid_clusters = np.sum(valid_clusters)
        assembly_contents = []
        for k in range(n_clusters):
            if valid_clusters[k]:
                assembly_contents.append(np.where(PI[:, k] >= 0.05)[0])
    else:
        n_valid_clusters = 0
        cluster_sizes = np.array([])
        assembly_contents = []
    if verbose:
        print(f'Number of valid clusters (size >= {min_cluster_size}): {n_valid_clusters}')
    results = {'SI': SI, 'eigenvalues': eigenvalues, 'eigenvectors': eigenvectors, 'n_clusters': n_valid_clusters, 'n_clusters_raw': n_clusters, 'correlation_matrix': corr_matrix, 'PI': PI, 'cluster_sizes': cluster_sizes[valid_clusters] if n_valid_clusters > 0 else np.array([]), 'assembly_contents': assembly_contents, 'corrSYN': SI[0] if len(SI) > 0 else 0.0, 'largest_eigenvalue': eigenvalues[0]}
    if fluorescence_data is not None:
        results['surrogate_mean'] = lambda_sur
        results['surrogate_std'] = SD_sur
        results['surrogate_eigenvalues'] = surrogate_eigenvalues
    return results
