"""Extract the SCA functions verbatim from the reference notebook into
assembloid_sync/_sca_reference.py. Keeps only imports and function defs (the cell also
contains a module-level demo invocation that must not run at import)."""
import ast
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WANTED = {"aaft_surrogate", "calculate_synchronicity_index"}

if len(sys.argv) < 2:
    sys.exit("usage: python tools/extract_reference.py <path to reference ROI_analysis.ipynb>")
NOTEBOOK = Path(sys.argv[1])

nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
src = None
for cell in nb["cells"]:
    text = "".join(cell["source"])
    if "def calculate_synchronicity_index" in text:
        src = text
        break
if src is None:
    sys.exit("calculate_synchronicity_index not found in " + str(NOTEBOOK))

tree = ast.parse(src)
keep = [n for n in tree.body
        if isinstance(n, (ast.Import, ast.ImportFrom))
        or (isinstance(n, ast.FunctionDef) and n.name in WANTED)]
names = {n.name for n in keep if isinstance(n, ast.FunctionDef)}
if names != WANTED:
    sys.exit("expected %s, found %s" % (WANTED, names))

out = REPO / "assembloid_sync" / "_sca_reference.py"
header = ('"""GENERATED by tools/extract_reference.py from\n%s\nDo not edit; '
          're-run the extractor instead."""\n' % NOTEBOOK.as_posix())
# the notebook cell relies on `np` imported in cell 0 - the module must import it itself
header += "import numpy as np\n"
out.write_text(header + ast.unparse(ast.Module(body=keep, type_ignores=[])) + "\n",
               encoding="utf-8")
print("wrote", out, "with", sorted(names))
